### ISSUE TITLE
Guide..

### ISSUE THREAD

**Issue by nmangones** [vixark/SimpleOps#2]
Please. do you have any installation or implementation guide?

**Comment by vixark** [comment]
Hello,

The project is not functional yet because it doesn't have UI, but the DIAN electronic invoicing works if you want to use SimpleOps as a third party DIAN electronic invocing app that communicates with any other ERP software via txt files. I have it working in production this way and it works just fine. If this fits your needs I can help you out to set it up.

**Comment by nmangones** [comment]
Hello!
I understand, your help to configure it would be good for me and I would appreciate it in advance.

**Comment by vixark** [comment]
I have to set up electronic invoicing for a company this month, so I will have to revisit the process and I will be able to make the guide. I will let you know when I upload it, maybe this or next week.

**Comment by vixark** [comment]
Hello,

I have already done the guide. It's in spanish, since its my language and the language that the futurer users of SimpleOps most likely speak. I think you can process it through a translator and you may follow it well enough. If you have any question you can ask me.

You can find the guide in the main page: https://github.com/vixark/SimpleOps

David
